config/routes.rb
GamingApp::Application.routes.draw do
  root "games#index"
  get '/games', to: 'games#index'
  get '/games/magic_8_ball', to: 'games#magic_8_ball', as: "magic_8_ball"
  get '/games/magic_8_ball/:question', to: 'games#magic_8_ball_play', as: 'magic_8_ball_play'
  get '/games/secret_number', to: 'games#secret_number', as: "secret_number"
  get '/games/secret_number/:guess', to: 'games#secret_number_play', as: "secret_number_play"
  get '/games/rock_paper_scissors/', to: 'games#rock_paper_scissors', as: "rps"
  get '/games/rock_paper_scissors/:throw', to: 'games#rock_paper_scissors_play', as: 'rps_play'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def index
    @games = {
      "Magic 8 Ball" => magic_8_ball_path,
      "Secret Number" => secret_number_path,
      "Rock Paper Scissors" => rps_path
    }

    @rps_description = %{Rock-paper-scissors is a hand game usually played by two people, where players simultaneously form one of three shapes with an outstretched hand. The "rock" beats scissors, the "scissors" beat paper and the "paper" beats rock; if both players throw the same shape, the game is tied. Other names for the game in the English-speaking world include roshambo, and other orderings of the three items.[1][2]
The game is often used as a choosing method in a way similar to coin flipping, drawing straws, or throwing dice. Unlike truly random selection methods, however, rock-paper-scissors can be played with a degree of skill by recognizing and exploiting non-random behavior in opponents}
  end

  def magic_8_ball
    if params[:question]
      redirect_to magic_8_ball_play_path(params[:question][:question])
    end
  end

  def magic_8_ball_play
    @question = params["question"].humanize.titleize + "?"
    fortunes = ["It is certain", "It is decidedly so", "Without a doubt", "Yes definitely",
     "You may rely on it", "As I see it yes", "Most likely", "Outlook good",
     "Yes", "Signs point to yes", "Reply hazy try again", "Ask again later",
     "Better not tell you now", "Cannot predict now", "Concentrate and ask again",
     "Don't count on it", "My reply is no", "My sources say no",
     "Outlook not so good", "Very doubtful"]
     @answer = fortunes.sample
   end

   def secret_number
   end

   def rock_paper_scissors

   end

   def rock_paper_scissors_play
    rps = {
      "rock" => "scissors",
      "scissor" => "paper",
      "paper" => "rock"
    }
    @your_throw = params[:throw]
    @rails_throw = ["rock", "paper", "scissors"].sample
    if @your_throw == @rails_throw
      @status = "Tie!"
    elsif rps[@your_throw] == @rails_throw
      @status = "Win"
    else
      @status = "Lose"
    end
  end

  def secret_number_play
    @guess = params[:guess].to_i
    @answer = rand(10) + 1
    if @guess == @answer
      render "win"
    else
      render 'lose'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
  def game_state(count, singular_state)
    if count == 1
      singular_state
    else
      'are'
    end
  end
end

app/views/games/index.html.erb
<h1>Welcome to the Game Center</h1>
<p>There <%= game_state @games.count, "is" %> <%=pluralize @games.count, 'game' %> available!</p>
<ul>
  <% @games.each do |game, path| %>
    <li><%= link_to game, path %></li>
  <% end %>
</ul>

<%= truncate @rps_description, length: 60, separator: " " %> <%= link_to "More", rps_path %>

app/views/games/lose.html.erb
<h1>Loser!</h1>
<%= image_tag 'loser.gif' %>

<%= link_to "Back", secret_number_path %>

app/views/games/magic_8_ball.html.erb
<h1>Magic 8 Ball!</h1>
<p>To play magic 8 ball go to http://localhost:3000/games/magic_8_ball/My Question!</p>
The game will give your fortune!

<%= form_for :question, method: 'get' do |f| %>
  <%= f.label "question" %>
  <%= f.text_field :question %>
  <%= f.submit %>
<% end %>

app/views/games/magic_8_ball_play.html.erb
<h1><%= @question %></h1>

<h2><%= @answer %></h2>

<p><%= link_to "Ask another question", magic_8_ball_path %></p>

app/views/games/rock_paper_scissors.html.erb
<h1>Rock Paper Scissors</h1>
Rock-paper-scissors is a hand game usually played by two people, where players simultaneously form one of three shapes with an outstretched hand. The "rock" beats scissors, the "scissors" beat paper and the "paper" beats rock; if both players throw the same shape, the game is tied. Other names for the game in the English-speaking world include roshambo, and other orderings of the three items.
The game is often used as a choosing method in a way similar to coin flipping, drawing straws, or throwing dice. Unlike truly random selection methods, however, rock-paper-scissors can be played with a degree of skill by recognizing and exploiting non-random behavior in opponents.

Click a link to play the game

<p><%= link_to "Throw Rock", rps_play_path('rock') %></p>
<p><%= link_to "Throw Paper", rps_play_path('paper') %></p>
<p><%= link_to "Throw Scissors",   rps_play_path('scissors') %></p>

app/views/games/rock_paper_scissors_play.html.erb
<h1>You threw <%= @your_throw %></h1>
Rails threw <%= @rails_throw %>
You <%= @status %>!!!

app/views/games/secret_number.html.erb
<h1>Secret Number won't die</h1>
<p>To play secret number go to</p>
<% 1.upto(10) do |guess| %>
<%= link_to "Guess #{guess}", secret_number_play_path(guess) %>
<% end %>

app/views/games/win.html.erb
<h1>You won!</h2>
<%= image_tag 'winner.gif' %>

<%= link_to "Back", secret_number_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GamingApp</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>